-- 内置接口模板的初始化 SQL —— 由 tools/gen-template-init-sql.mjs 从 src/lib/template-seed.ts 生成，别手改（--check 会盯漂移）
-- 只写 provider_template 这一张表：实例的取值（地址 / 密钥 / 模型）都在 provider.values_json 里，这份脚本不碰。
-- 可以反复执行（存在即覆盖成内置那一版），也可以只挑其中一条执行。
-- openai（llm）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('deepseek-chat', 'openai', 'llm', '{"modes":"sync"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://api.deepseek.com"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000}]', '{"submit":{"path":"${baseUrl}/chat/completions","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["deepseek-flash","deepseek-v4-pro"],"defaultValue":"deepseek-flash"},{"key":"reasoningEffort","label":"思考强度","valueType":"enum","options":["none","low","high","max"]},{"key":"thinking","label":"深度思考","valueType":"enum","options":["enabled","disabled"]},{"key":"temperature","label":"温度","valueType":"number","defaultValue":1,"min":0,"max":2,"step":0.1},{"key":"maxTokens","label":"最大输出 token","valueType":"number","defaultValue":200000},{"key":"systemPrompt","label":"系统提示词","valueType":"text"},{"key":"userPrompt","label":"用户提示词","valueType":"text"}],"body":{"model":"${model}","messages":[{"role":"system","content":"${systemPrompt}"},{"role":"user","content":"${userPrompt}"}],"stream":false,"reasoning_effort":"${reasoningEffort}","thinking":{"type":"${thinking}"},"temperature":"${temperature}","max_tokens":"${maxTokens}"},"outputs":{"content":"choices[0].message.content","errorCode":"error.code","error":"error.message"}}}', NULL, NULL, NULL, 0)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;

-- 千问 文生图（image）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('qwen-image', '千问 文生图', 'image', '{"modes":"both"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://maas.qianwenaiapi.com/api/v1"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000},{"key":"queryIntervalMs","label":"查询间隔 ms","valueType":"number","defaultValue":5000},{"key":"queryMaxAttempts","label":"查询次数上限","valueType":"number","defaultValue":360}]', '{"submit":{"path":"${baseUrl}/services/aigc/multimodal-generation/generation","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["qwen-image-3.0-pro"],"defaultValue":"qwen-image-3.0-pro"},{"key":"size","label":"出图尺寸","valueType":"string","defaultValue":"2048*2048"},{"key":"watermark","label":"水印","valueType":"boolean","defaultValue":false},{"key":"prompt","label":"画面描述","valueType":"text"}],"body":{"model":"${model}","input":{"messages":[{"role":"user","content":[{"text":"${prompt}"}]}]},"parameters":{"size":"${size}","watermark":"${watermark}"}},"artifactForm":"url","outputs":{"artifact":"output.choices[0].message.content[0].image","errorCode":"code","error":"message"}}}', '{"submit":{"path":"${baseUrl}/services/aigc/image-generation/generation","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}","X-DashScope-Async":"enable"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["qwen-image-3.0-pro"],"defaultValue":"qwen-image-3.0-pro"},{"key":"size","label":"出图尺寸","valueType":"string","defaultValue":"2048*2048"},{"key":"n","label":"张数","valueType":"number","defaultValue":1,"min":1,"max":4},{"key":"prompt","label":"画面描述","valueType":"text"}],"body":{"model":"${model}","input":{"messages":[{"role":"user","content":[{"text":"${prompt}"}]}]},"parameters":{"size":"${size}","n":"${n}"}},"outputs":{"taskId":"output.task_id","errorCode":"code","error":"message"}},"query":{"path":"${baseUrl}/tasks/${taskId}","method":"GET","headers":{"Authorization":"Bearer ${apiKey}"},"artifactForm":"url","outputs":{"status":"output.task_status","artifact":"output.choices[0].message.content[0].image","errorCode":"code","error":"message"},"successValues":["SUCCEEDED"],"failureValues":["FAILED","CANCELED","UNKNOWN"]}}', NULL, NULL, 1)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;

-- 千问 TTS（tts）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('qwen-tts', '千问 TTS', 'tts', '{"modes":"sync","clone":true,"cloneVia":"base64"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://maas.qianwenaiapi.com/api/v1"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000}]', '{"submit":{"path":"${baseUrl}/services/aigc/multimodal-generation/generation","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["qwen3-tts-flash","qwen3-tts-vc-2026-01-22"],"defaultValue":"qwen3-tts-flash"},{"key":"languageType","label":"语种","valueType":"enum","options":["Chinese","English","Auto"],"defaultValue":"Chinese"},{"key":"text","label":"合成文本","valueType":"text"},{"key":"voice","label":"音色 ID","valueType":"string","defaultValue":"Ethan"}],"body":{"model":"${model}","input":{"text":"${text}","voice":"${voice}","language_type":"${languageType}"}},"artifactForm":"url","outputs":{"artifact":"output.audio.url","errorCode":"code","error":"message"}}}', NULL, NULL, '{"path":"${baseUrl}/services/audio/tts/customization","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"复刻目标模型（须与合成同款）","valueType":"enum","options":["qwen3-tts-vc-2026-01-22"],"defaultValue":"qwen3-tts-vc-2026-01-22"},{"key":"preferredName","label":"音色名","valueType":"string","defaultValue":"mapvideo"}],"body":{"model":"qwen-voice-enrollment","input":{"action":"create","target_model":"${model}","preferred_name":"${preferredName}","audio":{"data":"${voiceData}"}}},"outputs":{"voiceId":"output.voice","errorCode":"code","error":"message"}}', 2)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;

-- ElevenLabs 语音（tts）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('elevenlabs-voice', 'ElevenLabs 语音', 'tts', '{"modes":"sync","clone":true,"cloneVia":"form"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://api.elevenlabs.io/v1"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000}]', '{"submit":{"path":"${baseUrl}/text-to-speech/${voice}","method":"POST","headers":{"Content-Type":"application/json","xi-api-key":"${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["eleven_multilingual_v2","eleven_flash_v2_5"],"defaultValue":"eleven_multilingual_v2"},{"key":"text","label":"合成文本","valueType":"text"},{"key":"voice","label":"音色 ID","valueType":"string","defaultValue":"CwhRBWXzGAHq8TQ4Fs17"}],"body":{"text":"${text}","model_id":"${model}"},"artifactForm":"binary","outputs":{"errorCode":"detail.code","error":"detail.message"}}}', NULL, NULL, '{"path":"${baseUrl}/voices/add","method":"POST","headers":{"xi-api-key":"${apiKey}"},"requestParams":[{"key":"preferredName","label":"音色名","valueType":"string","defaultValue":"mapvideo"}],"form":{"name":"${preferredName}","files":"${voiceData}"},"outputs":{"voiceId":"voice_id","errorCode":"detail.code","error":"detail.message"}}', 3)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;

-- MiniMax 语音（tts）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('minimax-voice', 'MiniMax 语音', 'tts', '{"modes":"sync","clone":true,"cloneVia":"upload"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://api.minimax.io/v1"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000}]', '{"submit":{"path":"${baseUrl}/t2a_v2","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["speech-2.8-hd","speech-2.8-turbo","speech-2.6-hd","speech-2.6-turbo","speech-02-hd","speech-02-turbo"],"defaultValue":"speech-2.8-hd"},{"key":"text","label":"合成文本","valueType":"text"},{"key":"voice","label":"音色 ID","valueType":"string","defaultValue":"male-qn-qingse"}],"body":{"model":"${model}","text":"${text}","voice_setting":{"voice_id":"${voice}"}},"artifactForm":"hex","outputs":{"artifact":"data.audio","errorCode":"base_resp.status_code","error":"base_resp.status_msg"}}}', NULL, '{"path":"${baseUrl}/files/upload","method":"POST","headers":{"Authorization":"Bearer ${apiKey}"},"form":{"purpose":"voice_clone","file":"${voiceData}"},"outputs":{"artifact":"file.file_id","errorCode":"base_resp.status_code","error":"base_resp.status_msg"}}', '{"path":"${baseUrl}/voice_clone","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"voiceId","label":"音色名（自己起 · 上游不回它）","valueType":"string","defaultValue":"mapvideo"}],"body":{"file_id":"${voiceData}","voice_id":"${voiceId}"},"outputs":{"errorCode":"base_resp.status_code","error":"base_resp.status_msg"}}', 4)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;

-- MiniMax 文生图（image）
INSERT INTO provider_template (tpl_id, name, category, caps_json, instance_params_json, sync_json, async_json, upload_json, clone_json, ord)
VALUES ('minimax-image', 'MiniMax 文生图', 'image', '{"modes":"sync"}', '[{"key":"baseUrl","label":"服务地址","valueType":"string","defaultValue":"https://api.minimax.io/v1"},{"key":"apiKey","label":"API Key","valueType":"secret"},{"key":"timeoutMs","label":"单次超时 ms","valueType":"number","defaultValue":60000}]', '{"submit":{"path":"${baseUrl}/image_generation","method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer ${apiKey}"},"requestParams":[{"key":"model","label":"模型","valueType":"enum","options":["image-01"],"defaultValue":"image-01"},{"key":"aspectRatio","label":"画幅","valueType":"enum","options":["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"],"defaultValue":"1:1"},{"key":"promptOptimizer","label":"提示词润色","valueType":"boolean","defaultValue":false},{"key":"prompt","label":"画面描述","valueType":"text"}],"body":{"model":"${model}","prompt":"${prompt}","aspect_ratio":"${aspectRatio}","prompt_optimizer":"${promptOptimizer}"},"artifactForm":"url","outputs":{"artifact":"data.image_urls[0]","errorCode":"base_resp.status_code","error":"base_resp.status_msg"}}}', NULL, NULL, NULL, 5)
ON CONFLICT(tpl_id) DO UPDATE SET name = excluded.name, category = excluded.category, caps_json = excluded.caps_json, instance_params_json = excluded.instance_params_json, sync_json = excluded.sync_json, async_json = excluded.async_json, upload_json = excluded.upload_json, clone_json = excluded.clone_json, ord = excluded.ord;
